---
- name: Install and configure AWS CloudWatch Unified Agent on Ubuntu
  hosts: all
  become: yes

  vars:
    aws_region: "eu-central-1"  # Specify your AWS region here
    log_group_name: "/var/log/my-application-log"  # Specify your CloudWatch log group
    log_file_path: "/var/log/my-application/*.log"  # Path to the log files you want to monitor

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - unzip
          - python3
          - python3-pip
        state: present

    - name: Download the latest CloudWatch Agent package
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dest: /tmp/amazon-cloudwatch-agent.deb

    - name: Install the CloudWatch Agent
      apt:
        deb: /tmp/amazon-cloudwatch-agent.deb
        state: present

    - name: Create CloudWatch Agent configuration file
      copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        content: |
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "{{ log_file_path }}",
                      "log_group_name": "{{ log_group_name }}",
                      "log_stream_name": "{instance_id}",
                      "timezone": "UTC"
                    }
                  ]
                }
              },
              "log_stream_name": "{instance_id}"
            }
          }

    - name: Start and enable the CloudWatch Agent
      command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json -s
      register: agent_start
      ignore_errors: no

    - name: Verify the CloudWatch Agent is running
      shell: ps aux | grep amazon-cloudwatch-agent
      register: agent_status

    - name: Output the status of the CloudWatch Agent
      debug:
        msg: "{{ agent_status.stdout_lines }}"
